=== FDKPIBC/PoESkillTree/UnitTests/TestBuilds/BuildUrls.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema
    xmlns:xs="http://www.w3.org/2001/XMLSchema"
>
  <!-- bandit - enumerable type -->
  <xs:simpleType name="bandit">
    <xs:restriction base="xs:string">
      <!-- None = 0 (poeplanner) -->
      <xs:enumeration value="None"/>
      <!-- Alira = 1 (poeplanner) -->
      <xs:enumeration value="Alira">
        <xs:annotation>
          <xs:documentation>
            +60 Mana (Normal); +5% Cast Speed (Cruel); +1 Power Charge (Merciless)
          </xs:documentation>
        </xs:annotation>
      </xs:enumeration>
      <!-- Oak = 2 (poeplanner - 3) -->
      <xs:enumeration value="Oak">
        <xs:annotation>
          <xs:documentation>
            +60 Life (Normal); +16% Physical Damage (Cruel); +1 Endurance Charge (Merciless)
          </xs:documentation>
        </xs:annotation>
      </xs:enumeration>
      <!-- Kraityn = 3 (poeplanner - 2) -->
      <xs:enumeration value="Kraityn">
        <xs:annotation>
          <xs:documentation>
            +10 all Res (Normal); +8% Attack Speed (Cruel); +1 Frenzy Charge (Merciless)
          </xs:documentation>
        </xs:annotation>
      </xs:enumeration>
    </xs:restriction>
  </xs:simpleType>

  <!-- url - anyURI type extended with 'name' and 'value' attributes -->
  <xs:complexType name="url">
    <xs:simpleContent>
      <xs:extension base="xs:string">
        <xs:attribute name="name" type="xs:string"/>
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>

  <!-- urls - contains default (primary) Url and optional alternative Urls -->
  <xs:element name="urls">
    <xs:annotation>
      <xs:documentation>
        Contains single default Url and multiple optional alternative Urls.
      </xs:documentation>
    </xs:annotation>
    <xs:complexType>
      <xs:sequence>
        <xs:element name="default" type="xs:string" minOccurs="1" maxOccurs="1" />
        <xs:element name="alternative" type="url" minOccurs="0" maxOccurs="unbounded"/>
      </xs:sequence>
    </xs:complexType>
    <xs:unique name="uniqueUrlName">
      <xs:selector xpath="alternative"/>
      <xs:field xpath="@name"/>
    </xs:unique>
    <xs:unique name="uniqueUrl">
      <xs:selector xpath=".//*"/>
      <xs:field xpath="."/>
    </xs:unique>
  </xs:element>

  <!-- bandits - tag, containing bandits selection -->
  <xs:element name="bandits">
    <xs:complexType>
      <xs:attribute name="normal" type="bandit" />
      <xs:attribute name="cruel" type="bandit"/>
      <xs:attribute name="merciless" type="bandit"/>
    </xs:complexType>
  </xs:element>

  <!-- document schema -->
  <xs:element name="testData">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="builds" maxOccurs="unbounded">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="build" maxOccurs="unbounded">
                <xs:complexType>
                  <xs:all>
                    <xs:element ref="urls"/>
                    <xs:element name="description" type="xs:token" minOccurs="0" maxOccurs="1"/>
                    <xs:element name="tags" type="xs:string" minOccurs="0" maxOccurs="1">
                      <xs:annotation>
                        <xs:documentation>
                          Contains multiple tokens, separated by a semicolon.
                          Tags can be used to find associated builds.
                        </xs:documentation>
                      </xs:annotation>
                    </xs:element>
                    <xs:element ref="bandits" minOccurs="0" maxOccurs="1"/>
                  </xs:all>
                  <xs:attribute name="name" type="xs:string" use="required"/>
                  <xs:attribute name="points" type="xs:integer"/>
                  <xs:attribute name="ascendancyPoints" type="xs:integer"/>
                  <xs:attribute name="treeVersion" type="xs:integer"/>
                  <xs:attribute name="characterClassId" type="xs:byte"/>
                  <xs:attribute name="ascendancyClassId" type="xs:byte"/>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
          <xs:unique name="uniqueBuildName">
            <xs:selector xpath="build"/>
            <xs:field xpath="@name"/>
          </xs:unique>
          <xs:unique name="uniqueBuildUrl">
            <xs:selector xpath="build/urls"/>
            <xs:field xpath="default"/>
          </xs:unique>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>

</xs:schema>

=== FDKPIBC/PoESkillTree/UnitTests/TestBuilds/EmptyBuildUrls.xml
<?xml version="1.0" encoding="utf-8" ?>
<testData
    xmlns:xs="http://www.w3.org/2001/XMLSchema-instance"
    xs:noNamespaceSchemaLocation="BuildUrls.xsd">
  <builds>
    <build name="Scion" characterClassId="0" ascendancyClassId="0">
      <urls>
        <default>https://www.pathofexile.com/passive-skill-tree/AAAABAAAAA==</default>
      </urls>
      <description>Starting build for Scion.</description>
      <tags>starting</tags>
    </build>
    <build name="ScionAscendant" characterClassId="0" ascendancyClassId="1">
      <urls>
        <default>https://www.pathofexile.com/passive-skill-tree/AAAABAABAA==</default>
      </urls>
      <description>Starting build for Scion - Ascendant.</description>
      <tags>starting</tags>
    </build>
    <build name="Marauder" characterClassId="1" ascendancyClassId="0">
      <urls>
        <default>https://www.pathofexile.com/passive-skill-tree/AAAABAEAAA==</default>
      </urls>
      <description>Starting build for Marauder.</description>
      <tags>starting</tags>
    </build>
    <build name="MarauderJuggernaut" characterClassId="1" ascendancyClassId="1">
      <urls>
        <default>https://www.pathofexile.com/passive-skill-tree/AAAABAEBAA==</default>
      </urls>
      <description>Starting build for Marauder Juggernaut.</description>
      <tags>starting</tags>
    </build>
    <build name="MarauderBerserker" characterClassId="1" ascendancyClassId="2">
      <urls>
        <default>https://www.pathofexile.com/passive-skill-tree/AAAABAECAA==</default>
      </urls>
      <description>Starting build for Marauder Berserker.</description>
      <tags>starting</tags>
    </build>
    <build name="MarauderChieftain" characterClassId="1" ascendancyClassId="3">
      <urls>
        <default>https://www.pathofexile.com/passive-skill-tree/AAAABAEDAA==</default>
      </urls>
      <description>Starting build for Marauder Chieftain.</description>
      <tags>starting</tags>
    </build>
    <build name="Ranger" characterClassId="2" ascendancyClassId="0">
      <urls>
        <default>https://www.pathofexile.com/passive-skill-tree/AAAABAIAAA==</default>
      </urls>
      <description>Starting build for Ranger.</description>
      <tags>starting</tags>
    </build>
    <build name="RangerRaider" characterClassId="2" ascendancyClassId="1">
      <urls>
        <default>https://www.pathofexile.com/passive-skill-tree/AAAABAIBAA==</default>
      </urls>
      <description>Starting build for Ranger Raider.</description>
      <tags>starting</tags>
    </build>
    <build name="RangerDeadeye" characterClassId="2" ascendancyClassId="2">
      <urls>
        <default>https://www.pathofexile.com/passive-skill-tree/AAAABAICAA==</default>
      </urls>
      <description>Starting build for Ranger Deadeye.</description>
      <tags>starting</tags>
    </build>
    <build name="RangerPathfinder" characterClassId="2" ascendancyClassId="3">
      <urls>
        <default>https://www.pathofexile.com/passive-skill-tree/AAAABAIDAA==</default>
      </urls>
      <description>Starting build for Ranger Pathfinder.</description>
      <tags>starting</tags>
    </build>
    <build name="Witch" characterClassId="3" ascendancyClassId="0">
      <urls>
        <default>https://www.pathofexile.com/passive-skill-tree/AAAABAMAAA==</default>
      </urls>
      <description>Starting build for Witch.</description>
      <tags>starting</tags>
    </build>
    <build name="WitchOccultist" characterClassId="3" ascendancyClassId="1">
      <urls>
        <default>https://www.pathofexile.com/passive-skill-tree/AAAABAMBAA==</default>
      </urls>
      <description>Starting build for Witch Occultist.</description>
      <tags>starting</tags>
    </build>
    <build name="WitchElementalist" characterClassId="3" ascendancyClassId="2">
      <urls>
        <default>https://www.pathofexile.com/passive-skill-tree/AAAABAMCAA==</default>
      </urls>
      <description>Starting build for Witch Elementalist.</description>
      <tags>starting</tags>
    </build>
    <build name="WitchNecromancer" characterClassId="3" ascendancyClassId="3">
      <urls>
        <default>https://www.pathofexile.com/passive-skill-tree/AAAABAMDAA==</default>
      </urls>
      <description>Starting build for Witch Necromancer.</description>
      <tags>starting</tags>
    </build>
    <build name="Duelist" characterClassId="4" ascendancyClassId="0">
      <urls>
        <default>https://www.pathofexile.com/passive-skill-tree/AAAABAQAAA==</default>
      </urls>
      <description>Starting build for Duelist.</description>
      <tags>starting</tags>
    </build>
    <build name="DuelistSlayer" characterClassId="4" ascendancyClassId="1">
      <urls>
        <default>https://www.pathofexile.com/passive-skill-tree/AAAABAQBAA==</default>
      </urls>
      <description>Starting build for Duelist Slayer.</description>
      <tags>starting</tags>
    </build>
    <build name="DuelistGladiator" characterClassId="4" ascendancyClassId="2">
      <urls>
        <default>https://www.pathofexile.com/passive-skill-tree/AAAABAQCAA==</default>
      </urls>
      <description>Starting build for Duelist Gladiator.</description>
      <tags>starting</tags>
    </build>
    <build name="DuelistChampion" characterClassId="4" ascendancyClassId="3">
      <urls>
        <default>https://www.pathofexile.com/passive-skill-tree/AAAABAQDAA==</default>
      </urls>
      <description>Starting build for Duelist Champion.</description>
      <tags>starting</tags>
    </build>
    <build name="Templar" characterClassId="5" ascendancyClassId="0">
      <urls>
        <default>https://www.pathofexile.com/passive-skill-tree/AAAABAUAAA==</default>
      </urls>
      <description>Starting build for Templar.</description>
      <tags>starting</tags>
    </build>
    <build name="TemplarInquisitor" characterClassId="5" ascendancyClassId="1">
      <urls>
        <default>https://www.pathofexile.com/passive-skill-tree/AAAABAUBAA==</default>
      </urls>
      <description>Starting build for Templar Inquisitor.</description>
      <tags>starting</tags>
    </build>
    <build name="TemplarHierophant" characterClassId="5" ascendancyClassId="2">
      <urls>
        <default>https://www.pathofexile.com/passive-skill-tree/AAAABAUCAA==</default>
      </urls>
      <description>Starting build for Templar Hierophant.</description>
      <tags>starting</tags>
    </build>
    <build name="TemplarGuardian" characterClassId="5" ascendancyClassId="3">
      <urls>
        <default>https://www.pathofexile.com/passive-skill-tree/AAAABAUDAA==</default>
      </urls>
      <description>Starting build for Templar Guardian.</description>
      <tags>starting</tags>
    </build>
    <build name="Shadow" characterClassId="6" ascendancyClassId="0">
      <urls>
        <default>https://www.pathofexile.com/passive-skill-tree/AAAABAYAAA==</default>
      </urls>
      <description>Starting build for Shadow.</description>
      <tags>starting</tags>
    </build>
    <build name="ShadowAssassin" characterClassId="6" ascendancyClassId="1">
      <urls>
        <default>https://www.pathofexile.com/passive-skill-tree/AAAABAYBAA==</default>
      </urls>
      <description>Starting build for Shadow Assassin.</description>
      <tags>starting</tags>
    </build>
    <build name="ShadowTrickster" characterClassId="6" ascendancyClassId="2">
      <urls>
        <default>https://www.pathofexile.com/passive-skill-tree/AAAABAYCAA==</default>
      </urls>
      <description>Starting build for Shadow Trickster.</description>
      <tags>starting</tags>
    </build>
    <build name="ShadowSaboteur" characterClassId="6" ascendancyClassId="3">
      <urls>
        <default>https://www.pathofexile.com/passive-skill-tree/AAAABAYDAA==</default>
      </urls>
      <description>Starting build for Shadow Saboteur.</description>
      <tags>starting</tags>
    </build>
  </builds>
</testData>
